spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/cook_recipe
    username: sr #sr
    password: 1234 #1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate:
      type:
        descriptor:
          sql: trace
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
    session:
      tracking-modes: cookie